/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: victorcalles (https://sketchfab.com/v3dartist)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/michi-bot-3de2985ed85e478387d2829b690d9523
Title: Michi Bot
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import botScene from "./Models/Bot.glb"

const Bot = (props)=>{
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(botScene)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} scale={[100, 100, 100]} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="9720a92d3b9a4d279bb7067fb9d66a02fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Geo">
                  <group name="Body" position={[0, -0.195, 0]}>
                    <mesh
                      name="Body_mat_michi_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Body_mat_michi_0.geometry}
                      material={materials.mat_michi}
                    />
                    <group name="AlaSup_Low1" position={[0.627, 0.389, 0]}>
                      <group
                        name="Wing_Up_I"
                        position={[-0.627, -0.427, 0]}
                        rotation={[0, 0.436, 0]}>
                        <group name="Wing_Up_I_1" position={[0.515, 0.296, -0.012]}>
                          <mesh
                            name="Wing_Up_I_mat_michi_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Wing_Up_I_mat_michi_0.geometry}
                            material={materials.mat_michi}
                          />
                        </group>
                      </group>
                      <group
                        name="Wing_Up_D"
                        position={[-0.627, -0.427, 0]}
                        rotation={[0, -0.436, 0]}>
                        <group name="Wing_Up_D_1" position={[-0.515, 0.296, -0.012]}>
                          <mesh
                            name="Wing_Up_D_mat_michi_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Wing_Up_D_mat_michi_0.geometry}
                            material={materials.mat_michi}
                          />
                        </group>
                      </group>
                    </group>
                    <group name="Wing" position={[0.675, 0.203, 0]}>
                      <group
                        name="Wing_Down_I"
                        position={[-0.675, -0.241, 0]}
                        rotation={[0, 0.436, 0]}>
                        <group name="Wing_Down_I_1" position={[0.589, 0.199, -0.012]}>
                          <mesh
                            name="Wing_Down_I_mat_michi_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Wing_Down_I_mat_michi_0.geometry}
                            material={materials.mat_michi}
                          />
                        </group>
                      </group>
                      <group
                        name="Wing_Down_D"
                        position={[-0.675, -0.241, 0]}
                        rotation={[0, -0.436, 0]}>
                        <group
                          name="Wing_Down_D_1"
                          position={[-0.589, 0.199, -0.012]}
                          rotation={[-0.122, -0.592, -0.068]}>
                          <mesh
                            name="Wing_Down_D_mat_michi_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Wing_Down_D_mat_michi_0.geometry}
                            material={materials.mat_michi}
                          />
                        </group>
                      </group>
                    </group>
                    <group name="Shoulder" position={[0, 0.395, 0]}>
                      <group
                        name="Shoulder_I"
                        position={[0.394, -0.308, 0.056]}
                        rotation={[-0.857, 0.002, -0.004]}>
                        <mesh
                          name="Shoulder_I_mat_michi_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Shoulder_I_mat_michi_0.geometry}
                          material={materials.mat_michi}
                        />
                        <group
                          name="Cannon_I"
                          position={[0.058, 0.001, 0.052]}
                          rotation={[-0.009, 0.131, 0.151]}>
                          <mesh
                            name="Cannon_I_mat_michi_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cannon_I_mat_michi_0.geometry}
                            material={materials.mat_michi}
                          />
                        </group>
                      </group>
                      <group
                        name="Shoulder_D"
                        position={[-0.394, -0.308, 0.056]}
                        rotation={[-0.672, 0.275, 0.13]}>
                        <mesh
                          name="Shoulder_D_mat_michi_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Shoulder_D_mat_michi_0.geometry}
                          material={materials.mat_michi}
                        />
                        <group name="Cannon_D" position={[0.394, 0.308, -0.056]}>
                          <mesh
                            name="Cannon_D_mat_michi_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cannon_D_mat_michi_0.geometry}
                            material={materials.mat_michi}
                          />
                        </group>
                      </group>
                    </group>
                    <group name="Cannon" position={[0, 0.395, 0]} />
                    <group name="Head" position={[0, 0.306, 0.088]} rotation={[0, Math.PI / 9, 0]}>
                      <mesh
                        name="Head_mat_michi_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Head_mat_michi_0.geometry}
                        material={materials.mat_michi}
                      />
                      <group name="Head_Prop" position={[0, 0.089, -0.088]}>
                        <mesh
                          name="Head_Prop_mat_michi_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Head_Prop_mat_michi_0.geometry}
                          material={materials.mat_michi}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Bot


